[tool.poetry]
name = "rf2-settings-widget"
version = "1.4.1"
description = ""
authors = ["Stefan Tapper <tapper.stefan@gmail.com>"]
readme = "README.md"
packages = [{include = "rf_video_settings"}]


[[tool.poetry.source]]
name = "piwigo"
url = "https://piwigo.ilikeviecher.com/ftp-upload/packages/"
secondary = true


[tool.poetry.dependencies]
python = ">=3.8,<3.12"
eel = {version = "==0.14.1", source = "piwigo"}  # See fork https://github.com/tappi287/Eel
appdirs = "^1.4.4"
pygame = "^2.1.2"
python-a2s = "^1.3.0"
psutil = "^5.9.3"
google-api-python-client = "^2.65.0"


[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.6.1"


[tool.poetry.group.openvr.dependencies]
ruamel-yaml = "^0.17.21"



[tool.poetry.group.youtube.dependencies]
google-auth-oauthlib = "^0.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
